### PR TITLE
SL-617: build the Unregistered Babies table

### PR DESCRIPTION
**Pull request by cioan**
@mogoodrich , here is the Unregistered Babies table that display the Labour and Delivery encounters with "Baby registered in EMR" obs set to No:

Screenshot 2024-06-11 at 6 12 39 AM

### CODE REVIEW

**Review by mogoodrich — COMMENTED** [review]
@cioan  generally looks good to me, thanks... one question, though, is it possible to have more than one baby on a single delivery form, ie twins, etc ?   it doesn't look like the GSP would handle this properly, if that were the case?

**Comment by cioan** [comment]
Thanks @mogoodrich ! That's a good observation! I will update the PR to cover the use case for twins. Thanks!

**Comment by cioan** [comment]
@mogoodrich , I have updated the PR to accommodate multiple babies within the same delivery form:

Screenshot 2024-06-11 at 3 38 34 PM

**Comment by cioan** [comment]
@mogoodrich , post commit comments are welcome.

**Review by mogoodrich — COMMENTED** [review]
LGTM, thanks @cioan !

**Pull request merged**
