### PR TITLE
LIB: addition of side effects to the mental health form

### PR DESCRIPTION
**Pull request by BranfordTGbieor**
LIB: addition of side effects to the mental health form

### CODE REVIEW

**Comment by lnball** [comment]
@alaboso @BranfordTGbieor Did you use Transifex?  The spanish (es), french (fr), haitian kreyol (ht) files show a new line character and not sure if those files will be processed properly.  The English messages.properties file looks fine.

**Comment by BranfordTGbieor** [comment]
> @alaboso @BranfordTGbieor Did you use Transifex? The spanish (es), french (fr), haitian kreyol (ht) files show a new line character and not sure if those files will be processed properly. The English messages.properties file looks fine.

Hi @lnball, the unnecessary new line characters that were earlier shown has now been removed.

**Comment by lnball** [comment]
@BranfordTGbieor Are you using Transifex?  You should not manually edit the spanish (es), french (fr), haitian kreyol (ht) message property files -- only the English one.  

FYI @alaboso @mogoodrich

**Comment by lnball** [comment]
Looks good

**Comment by lnball** [comment]
@Jilouwikyky has been making updates to the messages*.properties files using Transifex.

@BranfordTGbieor You don't need to add other languages, right?  

Looks good.

**Pull request merged**
