### PR TITLE
UHM-3863 Liquibase code to migrate the NCD diagnoses to use the const…

### PR DESCRIPTION
**Pull request by lnball**
@brandones Would you be so kind to review my migration code?  I'd be glad to explain further.

### CODE REVIEW

**Comment by brandones** [comment]
Sure! Will this code just be run once, or will it live forever as additional liquibase steps?

**Comment by lnball** [comment]
It will run once @brandones

**Comment by mogoodrich** [comment]
Yes, @brandones  if you look in the OpenMRS DB you see there's a liquibase table that tracks which changesets have already been run to assure that the same changeset doesn't run more than once.

**Comment by lnball** [comment]
@brandones It is a doozy.  And a good exercise to prove the rationale for good concept modeling from the start.  I wrote V1 and learned much before doing V2.  When in doubt -- use an obsgroup for valuable data.

As for hitting this sql if someone adds that concept, I have thought of that.  Not sure how to avoid -- unless I can have 2 preconditions -- one for Haiti (where the concept exists) and one for the concept.  I don't know how to do that.

**Comment by lnball** [comment]
Do **not** merge.  I need to change the code to migrate Type 2 DM to Type 2 DM on oral drugs.

**Comment by brandones** [comment]
Yep, per our discussion in the office last month, it should be left to the person who wrote the code to merge, since they'll have the best idea of when the right moment is, and the order in which things need to be done. Let me know when it's ready for another look.

**Comment by brandones** [comment]
> @brandones It is a doozy. And a good exercise to prove the rationale for good concept modeling from the start. I wrote V1 and learned much before doing V2. When in doubt -- use an obsgroup for valuable data.

I'd be really interested in hearing the story of what prompted this transition for Haiti. My experience with obsgroups has basically been that they make it impossible to use that data within OpenMRS, e.g. for graphs, ObsByEncounter, velocity lookups, etc.

> As for hitting this sql if someone adds that concept, I have thought of that. Not sure how to avoid -- unless I can have 2 preconditions -- one for Haiti (where the concept exists) and one for the concept. I don't know how to do that.

```
SELECT COUNT(*) FROM global_property gp
CROSS JOIN concept_name cn
WHERE gp.property_value LIKE '%haiti%'
    AND gp.property ='layout.address.format';
    AND cn.name LIKE 'Type 2 diabetes requiring insulin'
    AND cn.locale = 'en'
    AND cn.locale_preferred = 1
    AND cn.voided = 0;
```
?

As an aside, @mseaton , this seems to relate to the question of whether or not `pih.config` should be a global property. The SQL we're using to check the site here, with `layout.address.format`, is pretty fragile and awkward.

**Pull request closed without merging**
