### PR TITLE
Align template icons (expand, edit) on visit page

### PR DESCRIPTION
**Pull request by louidorjp**
I added a div in the appropriate files which included a class (pull-rigth) allowing to align the actions section on the right.
please accept my pull request.
@mogoodrich @lnball @mseaton

### CODE REVIEW

**Comment by brandones** [comment]
@mseaton this should be using BS4, right? In BS4 it's `float-right`, not `pull-right`. I imagine that `pull-right` is being defined somewhere in module-appframework.

**Comment by brandones** [comment]
Cool, thanks @louidorjp ! Could you add a screenshot?

dragging_images

**Comment by louidorjp** [comment]
[image: Screenshot from 2020-06-30 14-29-54.png]

Le mar. 30 juin 2020 à 14:10, Brandon Istenes <notifications@github.com> a
écrit :

**Comment by louidorjp** [comment]
> Cool, thanks @louidorjp ! Could you add a screenshot?
> 
> dragging_images

Screenshot from 2020-06-30 14-29-54

**Pull request merged**
