### PR TITLE
UHM-5520:  Remove custom Liberia metadata to config-pihliberia

### PR DESCRIPTION
**Pull request by mseaton**

### CODE REVIEW

**Review by mogoodrich — APPROVED** [review]
LGTM!

fyi @BranfordTGbieor  we are in the process of moving Patient Identifier and Encounter Type configuration out of code and into config, and this is the update for Liberia!

**Comment by BranfordTGbieor** [comment]
This is great! Thanks, @mogoodrich!!

**Comment by mogoodrich** [comment]
Thanks @BranfordTGbieor !  You can thank @mseaton  for doing this work!

**Comment by BranfordTGbieor** [comment]
Oh, my bad! Thank you too @mseaton!!😁

**Pull request merged**
